import type { Metadata } from "next";
import Link from 'next/link'

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <body className="main-container">
      <header className="header">
        <nav className="nav">
          <div className="nav-header-container">
            <Link className="nav-header" href="/"><h1>Швейно-вышивальная мастерская</h1></Link>
          </div>
          <div className="nav-links">
            <Link className="nav-link" href="/catalog">Catalog</Link>
            <Link className="nav-link" href="/about">About</Link>
          </div>
        </nav>
        <nav>


        </nav>
      </header>
      {children}
    </body>
  );
}
