import type { Metadata } from "next";
import Link from 'next/link'
import styles from './layout.module.css'

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <>
      <header className={styles.header}>
        <nav>
          <div>
            <Link className={styles.navLink} href="/"><h1>Швейно-вышивальная мастерская</h1></Link>
          </div>
          <div className={styles.navLinks}>
            <Link className={styles.navLink} href="/catalog">Catalog</Link>
            <Link className={styles.navLink} href="/about">About</Link>
            <Link className={styles.navLink} href="/admin">Admin</Link>
          </div>
        </nav>
      </header>
      {children}
    </>
  );
}
